#### 我们在浏览器控制台中运行foo'函数，是否会导致堆栈溢出错误？
```js
function foo(){
	setTimeout(foo, 0);
}
```
步骤:
- 调用 foo()会将foo函数放入调用堆栈。
- 在处理内部代码时，JS引擎遇到setTimeout。
- 然后将foo回调函数传递给WebAPIs并从函数返回，调用堆栈再次为空
- 计时器被设置为0，因此foo将被发送到任务队列。
- 由于调用堆栈是空的，事件循环将选择foo回调并将其推入调用堆栈进行处理。
`进程再次重复，堆栈不会溢出`

#### 如何实现下列代码：[1,2,a,b,c].abc(); // [1,2,a,b,c,1,2,a,b,c]
```js
Array.prototype.abc = function () {
  return this.concat(this);
}
let newArr = [1,2,3,4,5].abc()
console.log('newArr', newArr)
```